# -*- coding: utf-8 -*-
"""BreatCancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bVENG8ScZA9dX9a5Jm1PSRNHanJqgFe
"""

import pandas as pd
import numpy as np
import pathlib
from tqdm import tqdm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import plotly.express as px
from sklearn import preprocessing
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount("/content/drive")
# %cd /content/drive/My Drive/Machine Learning/

# Load the data
path = 'breast-cancer-diagnostic.shuf.lrn.csv'
dirPath = pathlib.Path(path)
df=pd.read_csv(dirPath)
print(df.head())

# Set class-label from true/false to 0/1
df['class'] = df['class'].astype(int)

# Split into input and target variables
X = df.iloc[:, 2:]  # Remove the ID and Class columns
Y = df.iloc[:, 1]

# Scale data
x = X.values # returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
#scaler = preprocessing.StandardScaler()
#x_scaled = scaler.fit_transform(x)
x_scaled = min_max_scaler.fit_transform(x)
df_x_scaled = pd.DataFrame(x_scaled)
print(df_x_scaled)

# Import test-data and scaling the data
pathTest = 'breast-cancer-diagnostic.shuf.tes.csv'
dirPathTest = pathlib.Path(pathTest)
df_test=pd.read_csv(dirPathTest)

xTest = df_test.iloc[:, 1:]  # Remove the ID and Class columns
x_test = xTest.values # returns a numpy array

min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x_test)

#scaler = preprocessing.StandardScaler()
#x_scaled = scaler.fit_transform(x_test)

df_test_normalized = pd.DataFrame(x_scaled)
print(df_test_normalized)

# Use the k-NN method (up to k_max) to predict the output variable on x_test, using the training data
def predict_knn(x_test, x_train, y_train, k_min=1, k_max=25):
    all_predictions = []
    for k in tqdm(range(k_min,k_max)):
        # Create KNN classifier
        knn = KNeighborsClassifier(n_neighbors=k,p=2)
        # Fit the classifier to the data
        knn.fit(x_train, y_train)
        # Predict on x_test
        prediction = knn.predict(x_test)
        all_predictions.append(prediction)
    return all_predictions

def predict_logistic_regression(x_test, x_train, y_train):
    all_predictions = []
    lr = LogisticRegression(random_state = 0)
    lr.fit(x_train, y_train)
    prediction = lr.predict(x_test)       
    all_predictions.append(prediction)
    return all_predictions

def predict_lda(x_test, x_train, y_train):
    all_predictions = []
    lda = LDA()
    lda.fit(x_train,y_train)
    prediction = lda.predict(x_test)
    all_predictions.append(prediction)
    return all_predictions

def predict_random_forrest(x_test, x_train, y_train, k_min=10, k_max=100):
    all_predictions = []
    for k in tqdm(range(k_min,k_max)):
        rndf = RandomForestClassifier(n_estimators=k)
        rndf.fit(x_train,y_train)
        prediction = rndf.predict(x_test)
        all_predictions.append(prediction)
    return all_predictions

def predict_qda(t_test, x_train, y_train):
    all_predictions = []
    qda = QuadraticDiscriminantAnalysis()
    qda.fit(x_train, y_train)
    prediction = qda.predict(x_test)
    all_predictions.append(prediction)
    return all_predictions

def predict_svm(x_test, x_train, y_train):
    all_predictions = []
    svc = svm.SVC()
    svc.fit(x_train, y_train)
    prediction = svc.predict(x_test)
    all_predictions.append(prediction)
    return all_predictions

def predict_naive_bayes(x_test, x_train, y_train):
    all_predictions = []
    gnb = GaussianNB()
    prediction = gnb.fit(X_train, Y_train).predict(X_test)
    all_predictions.append(prediction)
    return all_predictions

# Check the accuracy of given predictions on the test set y_test
def check_accuracy(y_test, predictions):
    ground_truth = y_test.to_list()
    size = len(ground_truth)
    results = []

    for predict in predictions:
        count = 0
        for i, x in enumerate(ground_truth):
            if predict[i] == ground_truth[i]:
                count += 1
        results.append(count / size)
    return results

# Training the different algorithms
X_train, X_test, Y_train, Y_test = train_test_split(df_x_scaled, Y, test_size=0.20, random_state=35)

# KNN
all_predictions = predict_knn(X_test, X_train, Y_train, 1, 30)
results = check_accuracy(Y_test, all_predictions)
print("\nTRAINING USING KNN")
max_value = max(results)
max_index = results.index(max_value)
print("Max value:", max_value)
print("Max index:", max_index)

# RANDOM FORREST
all_predictions = predict_random_forrest(X_test, X_train, Y_train, 1, 1000)
results = check_accuracy(Y_test, all_predictions)
print("\nTRAINING USING RANDOM FORREST")
max_value = max(results)
max_index = results.index(max_value)
print("Max value:", max_value)
print("Max index:", max_index)

# LOGISTIC REGRESSION
all_predictions = predict_logistic_regression(X_test, X_train, Y_train)
results = check_accuracy(Y_test, all_predictions)
print("\nTRAINING USING KNN")
print(results)

# LINEDAR DISCRIMINANT ANALYSIS
#all_predictions = predict_lda(X_test, X_train, Y_train)
#results = check_accuracy(Y_test, all_predictions)
#print("\nTRAINING USING LDA")
#print(results)

# QUADRATIC DISCRIMINANT ANALYSIS
all_predictions = predict_qda(X_test, X_train, Y_train)
results = check_accuracy(Y_test, all_predictions)
print("\nTRAINING USING QDA")
print(results)

# SUPPORT VECTOR MACHINES
all_predictions = predict_svm(X_test, X_train, Y_train)
results = check_accuracy(Y_test, all_predictions)
print("\nTRAINING USING SVM")
print(results)

# NAIVE BAYES
all_predictions = predict_naive_bayes(X_test, X_train, Y_train)
results = check_accuracy(Y_test, all_predictions)
print("\nTRAINING USING NAIVE BAYES")
print(results)

# TEST FOR KAGGLE (KNN)
knn = KNeighborsClassifier(n_neighbors=19,p=2)
knn.fit(df_x_scaled, Y)
prediction = knn.predict(df_test_normalized)

data = {'ID': df_test.iloc[:, 0], 'class': prediction}
output = pd.DataFrame(data, columns=['class'], index=data['ID'])
print(output)

# TEST FOR KAGGLE (LR)
LR = LogisticRegression(random_state = 0)
LR.fit(df_x_scaled, Y)
prediction = LR.predict(df_test_normalized)

data = {'ID': df_test.iloc[:, 0], 'class': prediction}
output = pd.DataFrame(data, columns=['class'], index=data['ID'])
print(output)

# Save
path = 'lr_breastcancer.csv'
dirPath = pathlib.Path(path)
output=output.to_csv(dirPath)